server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: products-service
        uri: lb://products-service
        predicates:
        - Path=/products/**
        filters:
        - RewritePath=/products/(?<path>.*), /$\{path}
      - id: customers-service
        uri: lb://customers-service
        predicates:
        - Path=/customers/**
        filters:
        - RewritePath=/customers/(?<path>.*), /$\{path}
      - id: reviews-service
        uri: lb://reviews-service
        predicates:
        - Path=/reviews/**
        filters:
        - RewritePath=/reviews/(?<path>.*), /$\{path}
      - id: payments-service
        uri: lb://payments-service
        predicates:
        - Path=/payments/**
        filters:
        - RewritePath=/payments/(?<path>.*), /$\{path}
      - id: orders-service
        uri: lb://orders-service
        predicates:
        - Path=/orders/**
        filters:
        - RewritePath=/orders/(?<path>.*), /$\{path}
      - id: sellers-service
        uri: lb://sellers-service
        predicates:
        - Path=/sellers/**
        filters:
        - RewritePath=/sellers/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs